{% set name = "pyregeon" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyregeon-{{ version }}.tar.gz
  sha256: 6af986c77570617afdd0d738a7117350264cc74c785788351c190dd9aa02dbd1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=1.0.0

test:
  imports:
    - pyregeon
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/martibosch/pyregeon
  summary: Reusable Python utilities to work with geospatial regions.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
