{% set name = "pyregeon" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyregeon-{{ version }}.tar.gz
  sha256: 23b9db4fdfd91d4f0e5ec945a2316f49d724a88c42cc97a4405df23bf6a59b8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9.4,<0.10.0
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=1.0.0

test:
  imports:
    - pyregeon
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/martibosch/pyregeon
  summary: Reusable Python utilities to work with geospatial regions.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
